-- ============================================================================
-- G13 Hospital Database System - Security Model (Roles & Privileges)
-- File: sql/04_security/roles_and_privileges.sql
-- Description: Establishes Role-Based Access Control (RBAC) by creating roles
--              (Admin, Doctor, Nurse, Receptionist, Billing) and granting
--              specific privileges.
-- ============================================================================

-- TODO: Create roles, assign table/view privileges, and define user accounts.
-- Example:
-- CREATE ROLE 'DoctorRole';
-- GRANT SELECT, INSERT, UPDATE ON Patients TO 'DoctorRole';
-- GRANT SELECT, INSERT ON Appointments TO 'DoctorRole';
