-- ============================================================================
-- G13 Hospital Database System - Triggers and Procedures
-- File: sql/05_views_triggers/trigger.sql
-- Description: Implement triggers for auditing, auto-incrementing, logic validation,
--              or automating billing calculations upon treatment entry.
-- ============================================================================

-- TODO: Create database triggers here. Example:
-- CREATE TRIGGER AuditPatientUpdates
-- AFTER UPDATE ON Patients
-- FOR EACH ROW
-- BEGIN
--     -- Insert old/new record details into AuditLog table
-- END;
